### PR TITLE
Support for --quiet and --dry-run options.

### PR DESCRIPTION
**Pull request by johntconklin**
This adds support for --quiet and --dry-run options, similar to "git clean".

### CODE REVIEW

**Comment by okcompute** [comment]
Hello John,

I'll work on merging your pull requests and fixing the bugs you found on monday.
Thank you very much for your collaboration on this project! It is greatly appreciated.

Pascal

**Comment by johntconklin** [comment]
Thanks Pascal,

Of the issues I've encountered so far, the most significant have been:
- os.chmod() changing the mode of files pointed to by symlinks to be removed
- downcasing filenames on case sensitive filesystems
- significant performance penalty (5-10x) of using p4 status compared to p4 fstat + os.walkdir()

I have these patched at work, and my developers are pretty happy with the results.  I'd be glad to help with fixes, but you'll need to provide some guidance of how you want to address these issues.  Let's use conversation thread for each issue to discuss.  Hopefully other p4clean users will join in as well.

**Comment by okcompute** [comment]
Hi John,

I made some changes for your commit and updated the tests. The feature is now in the master branch. Thank you!

**Comment by okcompute** [comment]
I think I solved all your issues. I will wait to test it out on a Windows machine tomorrow before creating a new release. Let me know if you see any problems with these changes on your side (if you can!).

Thanks again!

**Comment by johntconklin** [comment]
Pascal Lalancette notifications@github.com writes:

> I think I solved all your issues. I will wait to test it out on a
> Windows machine tomorrow before creating a new release. Let me know
> if you see any problems with these changes on your side (if you
> can!).

I should be able to roll out the git version to my developers
tomorrow. Waiting another day or two beyond that for feedback
should provide confidence that the new release will be a good
one.

```
--jtc
```

## 

J.T. Conklin

**Comment by okcompute** [comment]
I pushed new updated this morning. There was no log output and other bugs on windows platform (lchmod does not exist on windows! doh).

**Pull request merged**
